ST.Dental.Web/ViewModels/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ST.Dental.Web.ViewModels
{
  public class ContactViewModel
  {
    [Required]
    [MinLength(5)]
    public string Name { get; set; }
    [Required]
    [EmailAddress]
    public string Email { get; set; }
    [Required]
    public string Subject { get; set; }
    [Required]
    [MaxLength(250, ErrorMessage = "Too Long")]
    public string Message { get; set; }
  }
}

ST.Dental.Web/Controllers/FaqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ST.Dental.Web.Controllers
{
    public class FaqController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ST.Dental.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ST.Dental.Web.Models;

namespace ST.Dental.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Faq()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ST.Dental.Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ST.Dental.Web.Controllers
{
    public class SearchController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ST.Dental.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ST.Dental.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ST.Dental.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="hero_home version_2">
    <div class="content">
        <h3>Find a Dentist near me</h3>
        <p>
            Search for dentists near you offering our payment plans.
        </p>
        <form method="post" asp-controller="Search" asp-action="Index">
            <div id="custom-search-input">
                <div class="input-group">
                    <input type="text" class="search-query" placeholder="Ex. Postcode, Town ....">
                    <input type="submit" class="btn_search" value="Search">
                </div>
                <ul>
                    <li>
                        <input type="radio" id="all" name="radio_search" value="all" checked>
                        <label for="all">All</label>
                    </li>
                    <li>
                        <input type="radio" id="doctor" name="radio_search" value="doctor">
                        <label for="doctor">Dentist</label>
                    </li>
                    <li>
                        <input type="radio" id="clinic" name="radio_search" value="clinic">
                        <label for="clinic">Surgery</label>
                    </li>
                </ul>
            </div>
        </form>
    </div>
</div>


<div class="container margin_120_95">
    <div class="main_title">
        <h2>Find by specialization</h2>
        <p>Nec graeci sadipscing disputationi ne, mea ea nonumes percipitur. Nonumy ponderum oporteat cu mel, pro movet cetero at.</p>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <a href="list.html" class="box_cat_home">
                <i class="icon-info-4"></i>
                <img src="/images/gp/icon_cat_1.svg" width="60" height="60" alt="">
                <h3>Primary Care</h3>
                <ul class="clearfix">
                    <li><strong>124</strong>Doctors</li>
                    <li><strong>60</strong>Clinics</li>
                </ul>
            </a>
        </div>
        <div class="col-lg-3 col-md-6">
            <a href="list.html" class="box_cat_home">
                <i class="icon-info-4"></i>
                <img src="/images/gp/icon_cat_2.svg" width="60" height="60" alt="">
                <h3>Cardiology</h3>
                <ul class="clearfix">
                    <li><strong>124</strong>Doctors</li>
                    <li><strong>60</strong>Clinics</li>
                </ul>
            </a>
        </div>
        <div class="col-lg-3 col-md-6">
            <a href="list.html" class="box_cat_home">
                <i class="icon-info-4"></i>
                <img src="/images/gp/icon_cat_3.svg" width="60" height="60" alt="">
                <h3>MRI Resonance</h3>
                <ul class="clearfix">
                    <li><strong>124</strong>Doctors</li>
                    <li><strong>60</strong>Clinics</li>
                </ul>
            </a>
        </div>
        <div class="col-lg-3 col-md-6">
            <a href="list.html" class="box_cat_home">
                <i class="icon-info-4"></i>
                <img src="/images/gp/icon_cat_4.svg" width="60" height="60" alt="">
                <h3>Blood test</h3>
                <ul class="clearfix">
                    <li><strong>124</strong>Doctors</li>
                    <li><strong>60</strong>Clinics</li>
                </ul>
            </a>
        </div>
        <div class="col-lg-3 col-md-6">
            <a href="list.html" class="box_cat_home">
                <i class="icon-info-4"></i>
                <img src="/images/gp/icon_cat_7.svg" width="60" height="60" alt="">
                <h3>Laboratory</h3>
                <ul class="clearfix">
                    <li><strong>124</strong>Doctors</li>
                    <li><strong>60</strong>Clinics</li>
                </ul>
            </a>
        </div>
        <div class="col-lg-3 col-md-6">
            <a href="list.html" class="box_cat_home">
                <i class="icon-info-4"></i>
                <img src="/images/gp/icon_cat_5.svg" width="60" height="60" alt="">
                <h3>Dentistry</h3>
                <ul class="clearfix">
                    <li><strong>124</strong>Doctors</li>
                    <li><strong>60</strong>Clinics</li>
                </ul>
            </a>
        </div>
        <div class="col-lg-3 col-md-6">
            <a href="list.html" class="box_cat_home">
                <i class="icon-info-4"></i>
                <img src="/images/gp/icon_cat_6.svg" width="60" height="60" alt="">
                <h3>X - Ray</h3>
                <ul class="clearfix">
                    <li><strong>124</strong>Doctors</li>
                    <li><strong>60</strong>Clinics</li>
                </ul>
            </a>
        </div>
        <div class="col-lg-3 col-md-6">
            <a href="list.html" class="box_cat_home">
                <i class="icon-info-4"></i>
                <img src="/images/gp/icon_cat_8.svg" width="60" height="60" alt="">
                <h3>Piscologist</h3>
                <ul class="clearfix">
                    <li><strong>124</strong>Doctors</li>
                    <li><strong>60</strong>Clinics</li>
                </ul>
            </a>
        </div>
    </div>
    <!-- /row -->
</div>
<!-- /container -->


<div id="app_section">
    <div class="container">
        <div class="row justify-content-around">
            <div class="col-md-5">
                <p><img src="/images/gp/app_img.svg" alt="" class="img-fluid" width="500" height="433"></p>
            </div>
            <div class="col-md-6">
                <small>Application</small>
                <h3>Download <strong>Dentist App</strong> Now!</h3>
                <p class="lead">Tota omittantur necessitatibus mei ei. Quo paulo perfecto eu, errem percipit ponderum no eos. Has eu mazim sensibus. Ad nonumes dissentiunt qui, ei menandri electram eos. Nam iisque consequuntur cu.</p>
                <div class="app_buttons wow" data-wow-offset="100">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 43.1 85.9" style="enable-background:new 0 0 43.1 85.9;" xml:space="preserve">
                    <path stroke-linecap="round" stroke-linejoin="round" class="st0 draw-arrow" d="M11.3,2.5c-5.8,5-8.7,12.7-9,20.3s2,15.1,5.3,22c6.7,14,18,25.8,31.7,33.1" />

                    <path stroke-linecap="round" stroke-linejoin="round" class="draw-arrow tail-1" d="M40.6,78.1C39,71.3,37.2,64.6,35.2,58" />

                    <path stroke-linecap="round" stroke-linejoin="round" class="draw-arrow tail-2" d="M39.8,78.5c-7.2,1.7-14.3,3.3-21.5,4.9" />

                    </svg>
                    <a href="#0" class="fadeIn"><img src="/images/gp/apple_app.png" alt="" width="150" height="50" data-retina="true"></a>
                    <a href="#0" class="fadeIn"><img src="/images/gp/google_play_app.png" alt="" width="150" height="50" data-retina="true"></a>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /app_section -->